### ISSUE TITLE
city does not fill

### ISSUE THREAD

**Issue by tiagofunes** [insum-labs/apex-plugin-google-places-autocomplete#8]
Good morning, just my city that does not fill in some cases, mainly cities in Brazil. follow image.

![apex1](https://user-images.githubusercontent.com/36476717/36204298-e7e6e6f6-1171-11e8-9a2e-c068131d9301.PNG)

**Comment by tiagofunes** [comment]
I noticed that it may be Google that does not return correct, does it proceed?

**Comment by neilfernandez** [comment]
Currently we map certain fields that Google returns to us. This varies between countries and is dynamic from Google. Please look at the JSON returned to see exactly what Google returns to us. 

Feel free to use the our dynamic action custom event to retrieve the JSON returned and then map that to page items rather than using the built in options.

We map "locality" -> "City Page Item".

It looks like you do not have a locality(City) for the address you entered, it is considered "sublocality_level_1" instead. 

![2018-02-14_15h57_36](https://user-images.githubusercontent.com/9313239/36227705-ebea11aa-119f-11e8-8dd1-070f2766937a.png)

**Comment by tiagofunes** [comment]
some cases after I put the city and not address, more when I put address in Brazil and rare to bring all the data ... could you give me an example of how to make to correct? please

![image](https://user-images.githubusercontent.com/36476717/36253759-9e10977a-122f-11e8-878e-78cef40844f4.png)

**Comment by jrdad1** [comment]
I also get it for U.S. cities such as Brooklyn, NY

I enter 2115 Rockaway Parkway and select the one for Brooklyn
The city is not not populated with Brooklyn.

**Comment by neilfernandez** [comment]
@jrdad1 Thank you for reporting this. Feedback like this is vital for us to improve this plugin.

It seems it is the same issue for this address in Brooklyn:
![2018-03-06_15h49_02](https://user-images.githubusercontent.com/9313239/37057641-063aee06-2156-11e8-8b4d-e375a391fe40.png)

We will implement a feature if locality is not found, we will check for sublocality_level_1. This should fix that and will be in our next release.

**Comment by neilfernandez** [comment]
We now use sublocality_level_1 if it can not find locality, but this is not an end solution. IT is best to custom handle these situations so in the upcoming release we added a new custom event called place_changed_full_object as well. This allows the user to see the full object returned by google so they can parse the data how they need.
